### ISSUE TITLE
Creating schema.xml fails

### ISSUE THREAD

**Issue by brodul** [seut/readthedocs-buildout#2]
I got an error when running:

```
bin/manage build_solr_schema > parts/solr/solr/conf/schema.xml
```

Traceback:

```
[17/Jul/2012 06:50:12] DEBUG [tastyapi.slum:14] Using slumber with user test, pointed at http://localhost:8000
Traceback (most recent call last):
  File "/home/rtd/readthedocs-buildout/bin/manage-py", line 62, in <module>
    djangorecipe.manage.main('settings.sqlite')
  File "/home/rtd/readthedocs-buildout/eggs/djangorecipe-1.2.1-py2.7.egg/djangorecipe/manage.py", line 19, in main
    management.execute_manager(mod)
  File "/home/rtd/readthedocs-buildout/eggs/Django-1.4-py2.7.egg/django/core/management/__init__.py", line 459, in execute_manager
    utility.execute()
  File "/home/rtd/readthedocs-buildout/eggs/Django-1.4-py2.7.egg/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/rtd/readthedocs-buildout/eggs/Django-1.4-py2.7.egg/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/rtd/readthedocs-buildout/eggs/Django-1.4-py2.7.egg/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/home/rtd/readthedocs-buildout/eggs/django_haystack-2.0.0_beta-py2.7.egg/haystack/management/commands/build_solr_schema.py", line 21, in handle
    schema_xml = self.build_template(using=using)
  File "/home/rtd/readthedocs-buildout/eggs/django_haystack-2.0.0_beta-py2.7.egg/haystack/management/commands/build_solr_schema.py", line 43, in build_template
    c = self.build_context(using=using)
  File "/home/rtd/readthedocs-buildout/eggs/django_haystack-2.0.0_beta-py2.7.egg/haystack/management/commands/build_solr_schema.py", line 31, in build_context
    content_field_name, fields = backend.build_schema(connections[using].get_unified_index().all_searchfields())
  File "/home/rtd/readthedocs-buildout/eggs/django_haystack-2.0.0_beta-py2.7.egg/haystack/backends/__init__.py", line 172, in build_schema
    raise NotImplementedError("Subclasses must provide a way to build their schema.")
NotImplementedError: Subclasses must provide a way to build their schema.
```

**Comment by brodul** [comment]
Can you help me out?

**Comment by brodul** [comment]
I reported the bug to the RTD project. It's not a problem of buildout installation.
